#!/bin/bash

set -o errexit

[[ ${DEBUG} == true ]] && set -x

: ${SMTP_DOMAIN:?Missing environment variable}
: ${SMTP_PORT:=2525}
: ${SMTP_RELAY_HOST:?Missing environment variable}
: ${SMTP_RELAY_PORT:=25}
: ${SMTP_REGEX_SENDER:=.*@${SMTP_DOMAIN}}

cp /etc/slimta/slimta.yaml.in /etc/slimta/slimta.yaml
for e in SMTP_DOMAIN SMTP_PORT SMTP_RELAY_HOST SMTP_RELAY_PORT SMTP_REGEX_SENDER; do
    sed -e "s/%%${e}%%/${!e}/" -i /etc/slimta/slimta.yaml
done

[[ ${DEBUG} == true ]] && cat /etc/slimta/slimta.yaml

exec slimta --no-daemon
